name: Create artifact

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List files
        run: |
          pwd
          ll
          ls -R rtd_output || echo "No rtd_output directory"
      - name: Archive the docs
        uses: actions/upload-artifact@v4
        with:
          name: julia_docs
          path: rtd_output/html
